export { createColumnsBlock } from './columns'
export { reduceColumnsCommand } from './columns'
export type { ColumnsCommand } from './columns'
export { createId } from './data'
import { createTable } from './table'
import { createId } from './ids'
export const createTableBlock = (rows: number, columns: number) => createTable(rows, columns, createId, true)
export { getDocumentOutline } from './outline'
export { EDITOR_SCHEMA_VERSION, createEditorDocument, readEditorDocument, ensureStableIds } from './schema'
export { normalizedTableStructure } from './tableNormalization'
export { createTable, tableCellAt, tableMergeAt, tableCellAnchorAt, tableCellPresentationAt, mergedTableRegionAt, rectangularSelectionBounds, tableClipboardPayload, tableFromClipboard, parseTableClipboard, TABLE_CLIPBOARD_MIME } from './table'
export type { TableClipboardPayload, CellPoint, CellRange, CellBounds, MergedTableRegion, TableCellPresentation } from './table'
export { normalizeLinkUrl, getBlockDropDestination } from './editor'
export type * from './types'
export { reduceTableCommand } from './tableCommands'
export type { TableCommand } from './tableCommands'
export { assertUniqueIds } from './ids'
