import type { EditorLanguagePack } from './types'
import { uiChinese, uiEnglish } from './languageMessages'
export const zhCN: EditorLanguagePack = Object.freeze({ ...uiChinese, ...{
  'font.family': '字体', 'font.default': '默认字体', 'font.sans': '黑体', 'font.serif': '宋体', 'font.kai': '楷体', 'font.mono': '等宽', 'font.custom': '自定义字体',
  'table.axisBefore': '前方插入',
  'table.axisAfter': '后方插入',
  'table.insertColumnAt': '在第 {0} 个边界插入列',
  'table.insertRowAt': '在第 {0} 个边界插入行',
  'diagram.quickConnect': '快速接续节点',
  'diagram.connecttop': '在上方创建并连接节点',
  'diagram.connectright': '在右侧创建并连接节点',
  'diagram.connectbottom': '在下方创建并连接节点',
  'diagram.connectleft': '在左侧创建并连接节点',
  "placeholder": "输入内容，或输入 / 插入模块",
  "uploadImage": "上传图片",
  "uploadAttachment": "上传附件",
  "uploading": "上传中",
  "uploadFailed": "上传失败",
  "retry": "重试",
  "cancel": "取消",
  "download": "下载",
  "preview": "放大查看",
  "blocks": "基础模块",
  "noBlocks": "没有匹配的模块",
  "paragraph": "正文",
  "paragraphHint": "普通文本段落",
  "heading1": "一级标题",
  "heading1Hint": "页面主标题",
  "heading2": "二级标题",
  "heading2Hint": "章节标题",
  "todo": "待办事项",
  "todoHint": "可勾选的任务",
  "bulletList": "无序列表",
  "bulletListHint": "项目符号列表",
  "numberList": "有序列表",
  "numberListHint": "数字编号列表",
  "quote": "引用",
  "quoteHint": "突出引用内容",
  "codeBlock": "代码块",
  "codeBlockHint": "等宽代码区域",
  "divider": "分割线",
  "dividerHint": "分隔内容",
  "table": "表格",
  "tableHint": "选择 1 × 1 到 9 × 9",
  "image": "图片",
  "imageHint": "上传并等比缩放",
  "flowchart": "流程图",
  "flowchartHint": "基于 AntV X6",
  "mindmap": "思维导图",
  "mindmapHint": "可拖动的主题节点",
  "card": "卡片",
  "cardHint": "强调一组信息",
  "attachment": "附件",
  "attachmentHint": "上传文件"
} })
export const enUS: EditorLanguagePack = Object.freeze({ ...uiEnglish, ...{
  'font.family': 'Font family', 'font.default': 'Default', 'font.sans': 'Sans serif', 'font.serif': 'Serif', 'font.kai': 'Kai', 'font.mono': 'Monospace', 'font.custom': 'Custom font',
  'table.axisBefore': 'Insert before',
  'table.axisAfter': 'Insert after',
  'table.insertColumnAt': 'Insert column at boundary {0}',
  'table.insertRowAt': 'Insert row at boundary {0}',
  'diagram.quickConnect': 'Quick connect',
  'diagram.connecttop': 'Create and connect above',
  'diagram.connectright': 'Create and connect right',
  'diagram.connectbottom': 'Create and connect below',
  'diagram.connectleft': 'Create and connect left',
  "placeholder": "Type, or enter / to insert a block",
  "uploadImage": "Upload image",
  "uploadAttachment": "Upload attachment",
  "uploading": "Uploading",
  "uploadFailed": "Upload failed",
  "retry": "Retry",
  "cancel": "Cancel",
  "download": "Download",
  "preview": "Preview",
  "blocks": "Blocks",
  "noBlocks": "No matching blocks",
  "paragraph": "Text",
  "paragraphHint": "Plain text paragraph",
  "heading1": "Heading 1",
  "heading1Hint": "Page heading",
  "heading2": "Heading 2",
  "heading2Hint": "Section heading",
  "todo": "To-do",
  "todoHint": "Checkable task",
  "bulletList": "Bulleted list",
  "bulletListHint": "List with bullets",
  "numberList": "Numbered list",
  "numberListHint": "Ordered list",
  "quote": "Quote",
  "quoteHint": "Quoted content",
  "codeBlock": "Code block",
  "codeBlockHint": "Syntax-highlighted code",
  "divider": "Divider",
  "dividerHint": "Separate content",
  "table": "Table",
  "tableHint": "Choose 1 × 1 to 9 × 9",
  "image": "Image",
  "imageHint": "Upload and resize",
  "flowchart": "Flowchart",
  "flowchartHint": "Powered by AntV X6",
  "mindmap": "Mind map",
  "mindmapHint": "Draggable topic nodes",
  "card": "Card",
  "cardHint": "Highlight information",
  "attachment": "Attachment",
  "attachmentHint": "Upload a file"
} })
